// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYjUye4npbbDZdQnKyorNav08gIgn1_fg',
    appId: '1:12117966625:web:be05da851050275a2e4860',
    messagingSenderId: '12117966625',
    projectId: 'simple-app-f309d',
    authDomain: 'simple-app-f309d.firebaseapp.com',
    databaseURL: 'https://simple-app-f309d-default-rtdb.firebaseio.com',
    storageBucket: 'simple-app-f309d.firebasestorage.app',
    measurementId: 'G-H7LGYM13SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzKOqA3jUCr1M5AcCWqp7lpUkiTqivXSw',
    appId: '1:12117966625:android:bb471ec4e5b489312e4860',
    messagingSenderId: '12117966625',
    projectId: 'simple-app-f309d',
    databaseURL: 'https://simple-app-f309d-default-rtdb.firebaseio.com',
    storageBucket: 'simple-app-f309d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwisNIQdsUcmsYxk-3vwM0Er7PqexqomA',
    appId: '1:12117966625:ios:50a3383886b69d352e4860',
    messagingSenderId: '12117966625',
    projectId: 'simple-app-f309d',
    databaseURL: 'https://simple-app-f309d-default-rtdb.firebaseio.com',
    storageBucket: 'simple-app-f309d.firebasestorage.app',
    androidClientId: '12117966625-2blcn9e1bseacq254kds0nv758i0vvt2.apps.googleusercontent.com',
    iosClientId: '12117966625-var13jksfc5psai0nsq1o89vvu18kobq.apps.googleusercontent.com',
    iosBundleId: 'com.hydra.waterTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwisNIQdsUcmsYxk-3vwM0Er7PqexqomA',
    appId: '1:12117966625:ios:50a3383886b69d352e4860',
    messagingSenderId: '12117966625',
    projectId: 'simple-app-f309d',
    databaseURL: 'https://simple-app-f309d-default-rtdb.firebaseio.com',
    storageBucket: 'simple-app-f309d.firebasestorage.app',
    androidClientId: '12117966625-2blcn9e1bseacq254kds0nv758i0vvt2.apps.googleusercontent.com',
    iosClientId: '12117966625-var13jksfc5psai0nsq1o89vvu18kobq.apps.googleusercontent.com',
    iosBundleId: 'com.hydra.waterTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYjUye4npbbDZdQnKyorNav08gIgn1_fg',
    appId: '1:12117966625:web:ce04aef8a6c441cf2e4860',
    messagingSenderId: '12117966625',
    projectId: 'simple-app-f309d',
    authDomain: 'simple-app-f309d.firebaseapp.com',
    databaseURL: 'https://simple-app-f309d-default-rtdb.firebaseio.com',
    storageBucket: 'simple-app-f309d.firebasestorage.app',
    measurementId: 'G-3GHED9M1VN',
  );
}
